# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('CULTURAL', 'Cultural'), ('MEDIA', 'Media'), ('KNOWLEDGE', 'Knowledge'), ('DATA', 'Data')], default='', max_length=10)),
                ('description', models.CharField(default='An artifact', max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Category'),
        ),
    ]
