# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('CULTURAL', 'Cultural'), ('MEDIA', 'Media'), ('KNOWLEDGE', 'Knowledge'), ('DATA', 'Data')], default='', max_length=10)),
                ('description', models.CharField(default='An artifact', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artifacts.Category'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='current_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
